1.5: added missing table references
The following error was raised:
    raise exc.NoReferencedTableError(
sqlalchemy.exc.NoReferencedTableError: Foreign key associated with column 'story.user_id' could not find table 'user' with which to generate a foreign key to target column 'id'

The models couldn't find the table it was referencing for relationship.